output_dir: 'www/ui/compressed'
js:
  #phonegap_plugins:
    #files:
      #- 'ext/phonegap-plugins/iPhone/Badge/Badge.js'
      #- 'ext/phonegap-plugins/iPhone/ClipboardPlugin/clipboardPlugin.js'
  recurring:
    files:
      - 'www/ui/scripts/iscroll.js'
      - 'www/ui/scripts/spinningwheel.js'
      - 'www/ui/scripts/date.js'
      - 'www/ui/scripts/pretty.js'
      - 'www/models/task.js'
      - 'www/views/task_list.js'
      - 'www/views/edit_task.js'
      - 'www/controllers/task_list.js'
      - 'www/controllers/edit_task.js'
css:
  recurring:
    files:
      - 'www/ui/stylesheets/spinningwheel.css'
      - 'www/ui/stylesheets/common.css'
      - 'www/ui/stylesheets/task_list.css'
      - 'www/ui/stylesheets/edit_task.css'
