output_dir: 'www/ui/compressed'
js:
  phonegap_plugins:
    files:
      - 'ext/phonegap-plugins/iPhone/Badge/Badge.js'
      - 'ext/phonegap-plugins/iPhone/DatePicker/DatePicker.js'
      - 'ext/phonegap-plugins/iPhone/LocalNotification/LocalNotification.js'
  recurring:
    files:
      - 'www/ui/scripts/weinre.js'
      - 'www/views/mobile_fix.js'
      - 'www/ui/scripts/iscroll.js'
      - 'www/ui/scripts/date.js'
      - 'www/ui/scripts/pretty.js'
      - 'www/utilities/notifications.js'
      - 'www/models/task.js'
      - 'www/views/task_list.js'
      - 'www/views/edit_task.js'
      - 'www/controllers/task_list.js'
      - 'www/controllers/edit_task.js'
css:
  recurring:
    files:
      - 'www/ui/stylesheets/common.css'
      - 'www/ui/stylesheets/task_list.css'
      - 'www/ui/stylesheets/edit_task.css'
